"Disable arrow keys
noremap <Left> <NOP>
noremap <Right> <NOP>
noremap <Up> <NOP>
noremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>

"Enable scroll wheel for moving around
"This was useful on Ubuntu, but not necessary on the Mac
"map <ScrollWheelUp> 7k
"map <ScrollWheelDown> 7j

"Insert blank lines above or below by pressing Enter or backslash
nnoremap <silent> <Bslash> :<C-u>put =repeat(nr2char(10),v:count)<Bar>execute "'[-1"<CR>
nnoremap <silent> <Enter> :<C-u>put!=repeat(nr2char(10),v:count)<Bar>execute "']+1"<CR>

set number
set autoindent
set smartindent
set ruler
set laststatus=2
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set textwidth=0 
set wrapmargin=0
set tabpagemax=100
set bs=2
filetype plugin on

if has('mouse')
    set mouse=a
    set ttymouse=xterm2
endif


syntax enable
set background=dark
colorscheme solarized
