"Disable arrow keys
noremap <Left> <NOP>
noremap <Right> <NOP>
noremap <Up> <NOP>
noremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>

"Enable scroll wheel for moving around
"This was useful on Ubuntu, but not necessary on the Mac
"map <ScrollWheelUp> 7k
"map <ScrollWheelDown> 7j

"Insert blank lines above or below by pressing Enter or backslash
nnoremap <silent> <Bslash> :<C-u>put =repeat(nr2char(10),v:count)<Bar>execute "'[-1"<CR>
nnoremap <silent> <Enter> :<C-u>put!=repeat(nr2char(10),v:count)<Bar>execute "']+1"<CR>

"Show line numbers, (maybe) with relative numbering mode
set number
"set relativenumber

"Always show the status line at the bottom, even if you have only one window
"open
set laststatus=2

"The backspace key has slightly unintuitive behavior by default. For example,
"by default, you can't backspace before the insertion point set with 'i'.
"This configuration makes backspace behave more reasonably, in that you can
"backspace over anything.
set backspace=indent,eol,start

set autoindent
set smartindent
set ruler
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set textwidth=0 
set wrapmargin=0
set tabpagemax=100
set bs=2

"This setting makes search case-insensitive when all characters in the string
"being searched are lowercase. However, the search becomes case-sensitive if
"it contains any capital letters. This makes searching more convenient.
set ignorecase
set smartcase

"Wrap to next and previous lines when navigating left and right
set whichwrap+=<,>,h,l,[,]

"Enable searching as you type, rather than waiting until you press enter
set incsearch

"Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

"Disable audible bell
set noerrorbells visualbell t_vb=


filetype plugin on

if has('mouse')
    set mouse=a
    set ttymouse=xterm2
endif

"Enable syntax highlighting
syntax enable

"Set color scheme
set background=dark
colorscheme solarized

